name: Feature request
description: Suggest an idea for improving Dockhand
title: "[Feature Request] Concise description of the feature"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve?
      placeholder: Describe the problem you’re facing.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like it to work?
      placeholder: Describe your proposed solution.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you considered?
      placeholder: List alternatives if any.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots here.
      placeholder: Optional details.
    validations:
      required: false